In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b.shape

(3, 3)

In [6]:
# Works like a for loop
np.arange(1, 10 ,2)

array([1, 3, 5, 7, 9])

In [7]:
#Gives 4 numbers between 1 and 10 with eqaul spacing
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [9]:
np.array([[1, 2, 3.0], [4, 5, 6], [7, 8, 9]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
np.array([[1, 2, True], [4, False, 6], [7, 8, 9]])

array([[1, 2, 1],
       [4, 0, 6],
       [7, 8, 9]])

In [11]:
np.array([[1, 2, 3], ["S", 5, 6], [7, 8, 9]])

array([['1', '2', '3'],
       ['S', '5', '6'],
       ['7', '8', '9']], dtype='<U11')

In [12]:
b*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
np.concatenate((b, b*2), axis=1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [15]:
a = np.array([1, 2, 3, 4, 5])

In [18]:
f = open('txt.txt', 'w')
f.write(str(a))
f.close()

In [19]:
f = open('txt.txt', 'r')
f.read()

'[1 2 3 4 5]'